name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - master

env:
  AWS_REGION : "us-east-1"
  ECR_REPOSITORY_NAME: "abc"
  AWS_ACCOUNT_ID: 123

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04